# https://hydra.cc/docs/0.11/tutorial/config_groups/
nnet: "data-visualization-project/acas/networks"
training_data: "data-visualization-project/acas/TrainingData"
qtable: "data-visualization-project/acas/GenerateTable/Qtables"
logs: "data-visualization-project/logs"
plots: "data-visualization-project/plots"
tilde: "/idiap/user/kmatoba/"
