hcas:
  min_scaled_psi: 0.0
  max_scaled_psi: .50
  experiment_ident: "dataviz"

hardware:
  cuda_wanted: True
  benchmark: True

data:
  ndigit: 3
  num_rows_train: 9500
  num_rows_test: 500
  training_data_pattern: "{}_pra{:d}_tau{:02}.h5"
  vints: [100.0, 200.0, 300.0]
  vowns: [100.0, 200.0, 300.0]
  n_theta: 21
  n_psis: 21
  ranges: [0.0, 25.0, 50.0, 75.0, 100.0, 150.0, 200.0, 300.0, 400.0, 500.0, 510.0, 750.0, 1000.0, 1500.0,
           2000.0, 3000.0, 4000.0, 5000.0, 7000.0, 9000.0, 11000, 15000.0, 19000.0, 25000.0, 30000.0,
           35000.0, 40000.0, 48000.0, 56000.0]

prng:
  seed: 111

model:
  num_relu_layers: 5
  neurons_per_layer: 64
  include_bias: true
  ident_pattern: "pra{:d}_tau{:02d}_relulayers{:03d}_neurons{:03d}"

train:
  batch_size: 512
  lr: 4e-3
  num_epochs: 250
  test_size: 2000

torch:
  anomaly_detection: true
  deterministic: true
  dtype: float32

paths:
  nnet: "."
